"""Biblioteca de questões para provas de recrutamento.

Conteúdo próprio, revisável pelo RH. Cada questão declara matéria, nível e peso.
Níveis: 'operacional', 'junior', 'pleno', 'senior'. Uma questão vale para o nível
declarado e para os acima quando marcada com `tambem_acima`.

Tipos: 'choice' (múltipla escolha), 'truefalse', 'matching' (associação) e
'essay' (discursiva/redação, com rubrica de correção).
"""

SUBJECTS = {
    'portugues': 'Língua portuguesa e interpretação',
    'logica': 'Raciocínio lógico',
    'matematica': 'Matemática básica e quantitativa',
    'excel': 'Excel e planilhas',
    'informatica': 'Informática básica',
    'dp': 'Departamento pessoal e legislação trabalhista',
    'rh': 'Rotinas de recursos humanos',
    'atendimento': 'Atendimento e comunicação',
    'administrativo': 'Rotinas administrativas e financeiras',
    'redacao': 'Redação e produção de texto',
}

LEVELS = {
    'operacional': 'Operacional',
    'junior': 'Júnior / assistente',
    'pleno': 'Pleno / analista',
    'senior': 'Sênior / especialista',
}

def q(subject, level, kind, statement, weight=1, options=None, answer_key=None, rubric=None):
    return {'subject': subject, 'level': level, 'kind': kind, 'statement': statement,
            'weight': weight, 'options': options, 'answer_key': answer_key, 'rubric': rubric or []}

BANK = [
    # ---------------------------------------------------------------- português
    q('portugues', 'operacional', 'choice',
      'Assinale a frase escrita corretamente.',
      options=['Fazem dois anos que trabalho aqui.',
               'Faz dois anos que trabalho aqui.',
               'Fazem dois anos que trabalhamos aqui.',
               'Fazem-se dois anos que trabalho aqui.'],
      answer_key=1),
    q('portugues', 'operacional', 'choice',
      'Qual alternativa apresenta erro de ortografia?',
      options=['concerteza', 'exceção', 'privilégio', 'beneficente'],
      answer_key=0),
    q('portugues', 'junior', 'choice',
      'Leia: "Os documentos que foram entregues ontem ___ arquivados." Complete corretamente.',
      options=['foi', 'foram', 'fora', 'fôramos'],
      answer_key=1),
    q('portugues', 'junior', 'choice',
      'Em "O relatório foi entregue ao gestor, que o aprovou", o termo "o" em "aprovou" refere-se a:',
      options=['ao gestor', 'ao relatório', 'à entrega', 'à aprovação'],
      answer_key=1),
    q('portugues', 'junior', 'truefalse',
      'Em uma comunicação formal de trabalho, "anexo" concorda em gênero e número com o substantivo a que se refere. Exemplo correto: "Seguem anexas as planilhas."',
      answer_key=True),
    q('portugues', 'pleno', 'choice',
      'Assinale a opção em que a crase foi empregada corretamente.',
      options=['Enviei o documento à ele.',
               'Compareci à reunião de segunda-feira.',
               'Começamos à trabalhar cedo.',
               'Refiro-me à qualquer pessoa da equipe.'],
      answer_key=1),
    q('portugues', 'pleno', 'choice',
      'Leia o trecho: "Embora o prazo fosse curto, a equipe entregou o fechamento no dia combinado." A oração destacada por "Embora" exprime ideia de:',
      options=['causa', 'concessão', 'condição', 'finalidade'],
      answer_key=1),
    q('portugues', 'pleno', 'matching',
      'Associe cada expressão ao seu uso correto.', weight=2,
      options={'left': ['A fim de', 'Afim', 'Ao encontro de', 'De encontro a'],
               'right': ['Semelhante, que tem afinidade',
                         'Com a finalidade de',
                         'Em choque, contra',
                         'Em direção favorável a']},
      answer_key=[1, 0, 3, 2]),

    # ------------------------------------------------------------------ lógica
    q('logica', 'operacional', 'choice',
      'Em uma sequência, os números são: 2, 4, 8, 16, ... Qual é o próximo?',
      options=['18', '24', '32', '64'],
      answer_key=2),
    q('logica', 'junior', 'choice',
      'Se todo analista do setor usa crachá e João não usa crachá, conclui-se que:',
      options=['João é analista do setor.',
               'João não é analista do setor.',
               'Nenhum analista usa crachá.',
               'Não é possível concluir nada.'],
      answer_key=1),
    q('logica', 'junior', 'choice',
      'Complete a sequência: 3, 6, 11, 18, 27, ...',
      options=['36', '38', '40', '42'],
      answer_key=1),
    q('logica', 'pleno', 'choice',
      'A negação lógica de "Todos os colaboradores entregaram o relatório" é:',
      options=['Nenhum colaborador entregou o relatório.',
               'Pelo menos um colaborador não entregou o relatório.',
               'Todos os colaboradores não entregaram o relatório.',
               'Alguns colaboradores entregaram o relatório.'],
      answer_key=1),
    q('logica', 'pleno', 'choice',
      'Se "quando chove, o atendimento presencial cai" é verdadeiro, então necessariamente:',
      options=['Se o atendimento presencial caiu, choveu.',
               'Se não choveu, o atendimento presencial não caiu.',
               'Se o atendimento presencial não caiu, não choveu.',
               'Se choveu, o atendimento presencial subiu.'],
      answer_key=2),
    q('logica', 'senior', 'choice',
      'Três pessoas — Ana, Bruno e Carla — ocupam os cargos de analista, assistente e coordenadora, não necessariamente nessa ordem. Ana não é coordenadora. Bruno não é analista nem coordenador. Quem é a coordenadora?',
      options=['Ana', 'Bruno', 'Carla', 'Não é possível determinar'],
      answer_key=2),

    # -------------------------------------------------------------- matemática
    q('matematica', 'operacional', 'choice',
      'Um produto de R$ 80,00 recebeu desconto de 15%. Qual o valor final?',
      options=['R$ 64,00', 'R$ 68,00', 'R$ 70,00', 'R$ 72,00'],
      answer_key=1),
    q('matematica', 'operacional', 'choice',
      'Uma equipe de 4 pessoas produziu 120 atendimentos em um dia, com produção igual por pessoa. Quantos atendimentos fez cada uma?',
      options=['25', '30', '35', '40'],
      answer_key=1),
    q('matematica', 'junior', 'choice',
      'O salário de R$ 2.400,00 teve aumento de 8%. Qual o novo valor?',
      options=['R$ 2.560,00', 'R$ 2.592,00', 'R$ 2.620,00', 'R$ 2.688,00'],
      answer_key=1),
    q('matematica', 'junior', 'choice',
      'Em uma folha de 50 colaboradores, 12 têm vale-transporte. Qual o percentual?',
      options=['12%', '20%', '24%', '30%'],
      answer_key=2),
    q('matematica', 'pleno', 'choice',
      'Um colaborador com salário de R$ 3.000,00 fez 10 horas extras com adicional de 50%. Considerando 220 horas mensais, qual o valor das horas extras?',
      options=['R$ 136,36', 'R$ 150,00', 'R$ 204,55', 'R$ 227,27'],
      answer_key=2),
    q('matematica', 'pleno', 'choice',
      'O turnover de um mês foi de 4%. Em um quadro de 250 pessoas, quantos desligamentos isso representa?',
      options=['8', '10', '12', '15'],
      answer_key=1),

    # ------------------------------------------------------------------- excel
    q('excel', 'junior', 'choice',
      'Qual função procura um valor na primeira coluna de uma tabela e retorna um valor de outra coluna da mesma linha?',
      options=['SOMASE', 'PROCV', 'CONT.SE', 'ÍNDICE'],
      answer_key=1),
    q('excel', 'junior', 'choice',
      'Qual função conta quantas células de um intervalo atendem a um critério?',
      options=['CONT.NÚM', 'CONT.SE', 'SOMA', 'MÉDIA'],
      answer_key=1),
    q('excel', 'junior', 'truefalse',
      'Na fórmula =$A$1+B2, a referência $A$1 é absoluta e não muda quando a fórmula é copiada para outras células.',
      answer_key=True),
    q('excel', 'pleno', 'choice',
      'Para somar apenas os valores da coluna C cujos nomes na coluna A sejam "Filial 1", a função indicada é:',
      options=['SOMA', 'SOMASE', 'CONT.SE', 'SUBTOTAL'],
      answer_key=1),
    q('excel', 'pleno', 'choice',
      'Qual recurso resume grandes volumes de dados permitindo agrupar e totalizar por categoria, sem escrever fórmulas?',
      options=['Formatação condicional', 'Tabela dinâmica', 'Validação de dados', 'Congelar painéis'],
      answer_key=1),
    q('excel', 'pleno', 'matching',
      'Associe cada função ao que ela faz.', weight=2,
      options={'left': ['SE', 'PROCV', 'CONT.SE', 'ARRUMAR'],
               'right': ['Remove espaços extras de um texto',
                         'Testa uma condição e retorna um valor para verdadeiro e outro para falso',
                         'Conta ocorrências que atendem a um critério',
                         'Busca um valor e retorna o correspondente de outra coluna']},
      answer_key=[1, 3, 2, 0]),
    q('excel', 'senior', 'choice',
      'Qual combinação é mais robusta que o PROCV quando a coluna de busca não é a primeira da tabela?',
      options=['SOMA com SE', 'ÍNDICE com CORRESP', 'CONT.SE com SOMASE', 'PROCH com SOMA'],
      answer_key=1),

    # ------------------------------------------------------------- informática
    q('informatica', 'operacional', 'choice',
      'Qual atalho copia o conteúdo selecionado no Windows?',
      options=['Ctrl + X', 'Ctrl + C', 'Ctrl + V', 'Ctrl + Z'],
      answer_key=1),
    q('informatica', 'operacional', 'choice',
      'Em um e-mail, o campo Cco (cópia oculta) serve para:',
      options=['Enviar sem assunto',
               'Enviar cópia sem que os demais destinatários vejam esse endereço',
               'Marcar o e-mail como urgente',
               'Agendar o envio'],
      answer_key=1),
    q('informatica', 'junior', 'choice',
      'Qual formato preserva a formatação de um documento para envio e impressão, dificultando alterações acidentais?',
      options=['.docx', '.txt', '.pdf', '.csv'],
      answer_key=2),
    q('informatica', 'junior', 'truefalse',
      'Compartilhar a mesma senha entre vários colaboradores é uma prática aceitável desde que a equipe seja pequena.',
      answer_key=False),

    # ---------------------------------------------------- departamento pessoal
    q('dp', 'junior', 'choice',
      'O prazo legal para pagamento das verbas rescisórias, na maioria dos casos, é de:',
      options=['5 dias corridos', '10 dias corridos', '15 dias corridos', '30 dias corridos'],
      answer_key=1),
    q('dp', 'junior', 'truefalse',
      'O vale-transporte pode ser descontado do colaborador em até 6% do salário básico.',
      answer_key=True),
    q('dp', 'junior', 'choice',
      'O período aquisitivo de férias corresponde a:',
      options=['6 meses de trabalho', '12 meses de trabalho', '18 meses de trabalho', '24 meses de trabalho'],
      answer_key=1),
    q('dp', 'pleno', 'choice',
      'Sobre o fracionamento das férias após a Reforma Trabalhista, é correto afirmar que:',
      options=['Não é permitido em nenhuma hipótese.',
               'Pode ser dividido em até três períodos, sendo um deles de no mínimo 14 dias.',
               'Pode ser dividido livremente, sem período mínimo.',
               'Só pode ser dividido em dois períodos iguais.'],
      answer_key=1),
    q('dp', 'pleno', 'choice',
      'O adicional de hora extra previsto na Constituição, no mínimo, é de:',
      options=['20%', '30%', '50%', '100%'],
      answer_key=2),
    q('dp', 'pleno', 'choice',
      'O eSocial é utilizado para:',
      options=['Emitir notas fiscais de serviço',
               'Unificar o envio de informações trabalhistas, previdenciárias e fiscais ao governo',
               'Controlar o fluxo de caixa da empresa',
               'Registrar marcas e patentes'],
      answer_key=1),
    q('dp', 'pleno', 'matching',
      'Associe cada encargo à sua sigla.', weight=2,
      options={'left': ['Fundo de garantia do tempo de serviço',
                        'Contribuição previdenciária',
                        'Imposto sobre a renda retido na fonte'],
               'right': ['INSS', 'IRRF', 'FGTS']},
      answer_key=[2, 0, 1]),
    q('dp', 'senior', 'choice',
      'Na conferência de uma folha processada por contabilidade terceirizada, qual conjunto de itens deve ser confrontado antes da aprovação?',
      options=['Apenas o valor líquido total',
               'Base de cálculo, proventos, descontos, encargos e divergências de ponto',
               'Somente o número de colaboradores',
               'Apenas os adiantamentos'],
      answer_key=1),
    q('dp', 'senior', 'essay',
      'Descreva o passo a passo que você adota no fechamento mensal da folha quando o processamento é feito por contabilidade externa, incluindo prazos, conferências e tratamento de divergências.',
      weight=3,
      rubric=[{'name': 'Sequência e prazos do fechamento', 'max': 4},
              {'name': 'Conferências e controles citados', 'max': 3},
              {'name': 'Tratamento de divergências', 'max': 3}]),

    # ------------------------------------------------------------- rotinas RH
    q('rh', 'junior', 'choice',
      'Na admissão de um colaborador, qual documento é obrigatório para registro em carteira?',
      options=['Comprovante de vacinação',
               'Documento de identificação com CPF',
               'Certificado de curso de idiomas',
               'Declaração de imposto de renda'],
      answer_key=1),
    q('rh', 'pleno', 'choice',
      'O indicador de turnover mede:',
      options=['A satisfação da equipe',
               'A rotatividade de pessoal em um período',
               'O tempo médio de recrutamento',
               'O custo por contratação'],
      answer_key=1),
    q('rh', 'pleno', 'choice',
      'Em uma triagem de currículos, a prática mais adequada para reduzir viés é:',
      options=['Priorizar candidatos indicados por colaboradores',
               'Avaliar todos pelos mesmos critérios definidos antes da abertura da vaga',
               'Considerar a foto do candidato para avaliar perfil',
               'Descartar quem tem mais de dez anos de experiência'],
      answer_key=1),
    q('rh', 'pleno', 'truefalse',
      'Perguntar sobre estado civil, filhos ou planos de gravidez em entrevista é uma prática discriminatória e deve ser evitada.',
      answer_key=True),
    q('rh', 'senior', 'essay',
      'Uma vaga está aberta há 60 dias sem candidato aprovado. Descreva como você diagnosticaria o problema e quais ações tomaria, considerando divulgação, critérios da vaga, etapas do processo e alinhamento com o gestor requisitante.',
      weight=3,
      rubric=[{'name': 'Diagnóstico estruturado', 'max': 4},
              {'name': 'Ações propostas e viabilidade', 'max': 3},
              {'name': 'Alinhamento com o gestor e com o negócio', 'max': 3}]),

    # ------------------------------------------------------------- atendimento
    q('atendimento', 'operacional', 'choice',
      'Um cliente liga irritado por um atraso. Qual a primeira atitude adequada?',
      options=['Explicar imediatamente que a culpa foi de outro setor',
               'Ouvir sem interromper e confirmar o entendimento do problema',
               'Transferir a ligação para outro atendente',
               'Pedir que envie a reclamação por e-mail'],
      answer_key=1),
    q('atendimento', 'operacional', 'truefalse',
      'Prometer um prazo que provavelmente não será cumprido é aceitável para acalmar o cliente no momento da ligação.',
      answer_key=False),
    q('atendimento', 'junior', 'choice',
      'Ao registrar um atendimento no sistema, a informação mais importante a garantir é:',
      options=['Que o texto seja curto',
               'Que o registro descreva o ocorrido e o encaminhamento de forma objetiva e rastreável',
               'Que use abreviações para agilizar',
               'Que contenha a opinião pessoal do atendente'],
      answer_key=1),
    q('atendimento', 'junior', 'essay',
      'Escreva a resposta que você enviaria a um cliente que reclama de um atraso de cinco dias na entrega de um serviço contratado. A resposta deve reconhecer o problema, informar o encaminhamento e preservar a relação.',
      weight=2,
      rubric=[{'name': 'Clareza e cordialidade', 'max': 4},
              {'name': 'Reconhecimento do problema e solução proposta', 'max': 4},
              {'name': 'Correção da linguagem', 'max': 2}]),

    # ---------------------------------------------------------- administrativo
    q('administrativo', 'junior', 'choice',
      'Em um controle de contas a pagar, o que caracteriza um título vencido?',
      options=['Título com data de emissão anterior ao mês corrente',
               'Título cuja data de vencimento já passou sem pagamento',
               'Título com valor acima do orçamento',
               'Título pago antecipadamente'],
      answer_key=1),
    q('administrativo', 'junior', 'choice',
      'Qual documento comprova a prestação de um serviço para fins fiscais?',
      options=['Recibo simples', 'Nota fiscal de serviço', 'Ordem de compra', 'Boleto bancário'],
      answer_key=1),
    q('administrativo', 'pleno', 'choice',
      'Ao conciliar o extrato bancário com o sistema, uma diferença recorrente no mesmo valor todo mês indica, mais provavelmente:',
      options=['Erro de digitação pontual',
               'Lançamento recorrente não cadastrado no sistema',
               'Fraude bancária',
               'Problema no extrato do banco'],
      answer_key=1),

    # ---------------------------------------------------------------- redação
    q('redacao', 'junior', 'essay',
      'Escreva um texto de 15 a 25 linhas apresentando sua trajetória profissional e explicando por que se candidatou a esta vaga. Utilize a norma culta.',
      weight=3,
      rubric=[{'name': 'Norma culta (ortografia, concordância, pontuação)', 'max': 3},
              {'name': 'Clareza e organização das ideias', 'max': 3},
              {'name': 'Relação entre a trajetória e a vaga', 'max': 4}]),
    q('redacao', 'pleno', 'essay',
      'Descreva uma situação profissional em que você identificou um erro em um processo já estabelecido. Explique como percebeu o problema, o que propôs e qual foi o resultado.',
      weight=3,
      rubric=[{'name': 'Clareza na descrição da situação', 'max': 3},
              {'name': 'Capacidade analítica e proposta de solução', 'max': 4},
              {'name': 'Norma culta e organização', 'max': 3}]),
    q('redacao', 'senior', 'essay',
      'Redija um texto dissertativo de 20 a 30 linhas sobre o impacto da tecnologia nas rotinas administrativas, apresentando ao menos um ganho e um risco, com posicionamento fundamentado.',
      weight=4,
      rubric=[{'name': 'Norma culta', 'max': 2},
              {'name': 'Estrutura dissertativa (tese, argumentos, conclusão)', 'max': 3},
              {'name': 'Consistência dos argumentos', 'max': 3},
              {'name': 'Posicionamento fundamentado', 'max': 2}]),
]

# Modelos prontos: matérias e quantidade sugerida por perfil de vaga.
TEMPLATES = {
    'dp-pleno': {
        'title': 'Analista de Departamento Pessoal — Pleno',
        'level': 'pleno', 'duration_minutes': 90,
        'mix': [('dp', 6), ('excel', 4), ('portugues', 3), ('logica', 2), ('redacao', 1)],
    },
    'rh-generalista': {
        'title': 'Analista de RH Generalista',
        'level': 'pleno', 'duration_minutes': 90,
        'mix': [('rh', 4), ('dp', 4), ('portugues', 3), ('logica', 3), ('redacao', 1)],
    },
    'administrativo-junior': {
        'title': 'Assistente Administrativo — Júnior',
        'level': 'junior', 'duration_minutes': 60,
        'mix': [('administrativo', 3), ('excel', 3), ('portugues', 3), ('matematica', 3), ('informatica', 2)],
    },
    'atendimento-operacional': {
        'title': 'Operador de Atendimento — Operacional',
        'level': 'operacional', 'duration_minutes': 45,
        'mix': [('atendimento', 4), ('portugues', 3), ('matematica', 2), ('informatica', 2), ('redacao', 1)],
    },
    'triagem-geral': {
        'title': 'Triagem geral — conhecimentos básicos',
        'level': 'junior', 'duration_minutes': 45,
        'mix': [('portugues', 4), ('logica', 4), ('matematica', 3), ('informatica', 2)],
    },
}

ORDER = ['operacional', 'junior', 'pleno', 'senior']

def pool(subject, level):
    """Questões da matéria até o nível pedido: quem é pleno responde também o de júnior."""
    limit = ORDER.index(level) if level in ORDER else len(ORDER) - 1
    return [row for row in BANK if row['subject'] == subject and ORDER.index(row['level']) <= limit]

def assemble(mix, level):
    """Monta a lista de questões a partir de pares (matéria, quantidade)."""
    chosen, seen = [], set()
    for subject, amount in mix:
        available = [row for row in pool(subject, level) if id(row) not in seen]
        for row in available[:amount]:
            seen.add(id(row))
            chosen.append(row)
    return chosen
